repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: check-added-large-files

  - repo: https://github.com/pycqa/pylint
    rev: pylint-2.9.6
    hooks:
    -   id: pylint
        args: [--errors-only]

  - repo: https://github.com/psf/black
    rev: 21.9b0
    hooks:
    - id: black

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      types: [python]
      pass_filenames: false
