repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-added-large-files

  - repo: https://github.com/pycqa/pylint
    rev: v3.0.0a6  # Utilisez la version de pylint provenant de requirements.txt
    hooks:
    -   id: pylint

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    - id: black

  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: pytest
      language: system
      types: [python]
      pass_filenames: false
