name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

env:
  MYSQL_HOST: ${{ secrets.DATABASE_HOST }}
  MYSQL_DATABASE: ${{ secrets.DATABASE_NAME }}
  MYSQL_USER: ${{ secrets.DATABASE_USER }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-20.04
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

    env:
      CI: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Setup database
        run: |
          mysql -h ${{ secrets.MYSQL_HOST }} -u ${{ secrets.MYSQL_USER }} -p${{ secrets.MYSQL_ROOT_PASSWORD }} -e "CREATE DATABASE \`${{ secrets.MYSQL_DATABASE }}\`; USE \`${{ secrets.MYSQL_DATABASE }}\`; CREATE TABLE hvac_data (timestamp datetime not null, event longtext not null);"

      - name: Run unit tests
        env:
          HOST: ${{ secrets.HOST }}
          TICKETS: ${{ secrets.TICKETS }}
          TOKEN: ${{ secrets.TOKEN }}
          T_MAX: ${{ secrets.T_MAX }}
          T_MIN: ${{ secrets.T_MIN }}
        run: pytest

      - name: Build Docker image
        run: docker build -t oxygen:latest .

      - name: Publish Docker image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username hzsam --password-stdin
          docker tag oxygen:latest hzsam/myrepo:oxygen
          docker push hzsam/myrepo:oxygen
