name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

env:
  MYSQL_HOST: ${{ secrets.DATABASE_HOST }}
  MYSQL_DATABASE: ${{ secrets.DATABASE_NAME }}
  MYSQL_USER: ${{ secrets.DATABASE_USER }}
  MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
          MYSQL_DATABASE: ${{ secrets.DATABASE_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Set up Database
        env:
          MYSQL_HOST: ${{ secrets.DATABASE_HOST }}
          MYSQL_USER: ${{ secrets.DATABASE_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_ROOT_PASSWORD }}
        run: |
          mysql -h${MYSQL_HOST} -u${MYSQL_USER} -p${MYSQL_PASSWORD} -e "CREATE DATABASE IF NOT EXISTS ${MYSQL_DATABASE};"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        env:
          HOST: ${{ secrets.HOST }}
          TICKETS: ${{ secrets.TICKETS }}
          TOKEN: ${{ secrets.TOKEN }}
          T_MAX: ${{ secrets.T_MAX }}
          T_MIN: ${{ secrets.T_MIN }}
        run: pytest
