name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop # for testing purposes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run unit tests
        run: npm test

      - name: Static code analysis
        run: npm run lint

      - name: Build Docker image
        run: docker build -t myapp:latest .

      - name: Publish Docker image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username mahrez29 --password-stdin
          docker tag myapp:latest USERNAME/myapp:latest
          docker push USERNAME/myapp:latest
