name: CI/CD Pipeline
on:
  push:
    branches:
      - main
env:
  POSTGRES_HOST: 34.28.50.31
  POSTGRES_DB: oxygen7db
  POSTGRES_USER: team7
  POSTGRES_PASSWORD: team7

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: ${{ env.POSTGRES_DB }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install Alembic
        run: pip install alembic

      - name: Run PostgreSQL migrations
        env:
          DATABASE_HOST: ${{ job.services.postgres.ports[5432] }}
          DATABASE_NAME: ${{ env.POSTGRES_DB }}
          DATABASE_USER: ${{ env.POSTGRES_USER }}
          DATABASE_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: alembic upgrade head

      - name: Run unit tests
        env:
          DATABASE_HOST: ${{ job.services.postgres.ports[5432] }}
          DATABASE_NAME: ${{ env.POSTGRES_DB }}
          DATABASE_USER: ${{ env.POSTGRES_USER }}
          DATABASE_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        run: pytest

      - name: Build Docker image
        run: docker build -t oxygen:latest .

      - name: Publish Docker image
        run: |
          echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login --username hzsam --password-stdin
          docker tag oxygen:latest hzsam/myrepo:oxygen
          docker push hzsam/myrepo:oxygen
